name: Deploy website

on:
  push:
    branches:
    - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:

      - id: setup-gcloud
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - id: cli
        run: gcloud info

      - id: upload-files
        uses: google-github-actions/upload-cloud-storage@main
        with:
          path: .
          destination: white-ribbon-therapy
